# Generated by Django 3.0.5 on 2023-04-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='profile_pic',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
