# Generated by Django 3.0.5 on 2023-05-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_auto_20230503_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='vehicle_no',
            field=models.CharField(max_length=20),
        ),
    ]
