# Generated by Django 3.0.5 on 2023-05-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_auto_20230503_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Km_Driven',
            field=models.PositiveIntegerField(blank=True, max_length=40, null=True),
        ),
    ]
